[package]
name = "standalone-tests"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
stdweb = { path = ".." }
stdweb-derive = { path = "../stdweb-derive" }

serde = "1"
serde_derive = "1"

dependency = { path = "dependency" }
