[package]
name = "wasm-bindgen-minimal"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.40"
stdweb = { path = "../..", features = ["wasm-bindgen"] }
