[package]
name = "benchmarks"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
stdweb = { path = ".." }
lazy_static = "1"
serde = "1"
serde_derive = "1"

[build-dependencies]
rustc_version = "0.2"
